/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sisdespesas.view.internal;

import br.com.sisdespesas.classes.Alert;
import br.com.sisdespesas.classes.Exportar;
import br.com.sisdespesas.classes.Tabela;
import br.com.sisdespesas.controle.ControleUsuario;
import br.com.sisdespesas.view.modal.CadastroUsuario;
import java.awt.event.KeyEvent;
import javax.swing.JDialog;

/**
 *
 * @author AutoPecasLuz
 */
public class UsuarioLista extends javax.swing.JInternalFrame {

    /**
     * Creates new form CentroCustoLista
     */
    public UsuarioLista() {
        initComponents();
        String labels[] = {"Código", "Nome", "Situação"};
        String keys[] = {"ID_USUARIO", "NOME", "ATIVO"};
        Tabela.set(grid, txtBusca, labels, keys, btnFiltro, ControleUsuario.SQL, limite);
        Tabela.collWith(grid, 2, 80);
        Tabela.collAtivoInativo(grid, 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPopupMenu();
        btnEditar = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        btnDeletar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grid = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        txtBusca = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        btnFiltro = new javax.swing.JButton();
        limite = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnExportar = new javax.swing.JButton();

        menu.setBackground(new java.awt.Color(255, 255, 255));

        btnEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(49, 43, 103));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sisdespesas/img/pencil.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        menu.add(btnEditar);
        menu.add(jSeparator3);

        btnDeletar.setBackground(new java.awt.Color(255, 255, 255));
        btnDeletar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDeletar.setForeground(new java.awt.Color(49, 43, 103));
        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sisdespesas/img/trash.png"))); // NOI18N
        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        menu.add(btnDeletar);

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setClosable(true);
        setForeground(new java.awt.Color(49, 43, 103));
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Usuários");
        setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sisdespesas/img/circle.png"))); // NOI18N
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        grid.setAutoCreateRowSorter(true);
        grid.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        grid.setForeground(new java.awt.Color(49, 43, 103));
        grid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Ativo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grid.setColumnSelectionAllowed(true);
        grid.setComponentPopupMenu(menu);
        grid.setGridColor(new java.awt.Color(229, 229, 229));
        grid.setRowHeight(24);
        grid.setRowMargin(4);
        grid.setSelectionBackground(new java.awt.Color(217, 215, 238));
        grid.setSelectionForeground(new java.awt.Color(49, 43, 103));
        grid.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        grid.getTableHeader().setReorderingAllowed(false);
        grid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridMouseClicked(evt);
            }
        });
        grid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gridKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gridKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(grid);
        grid.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(49, 43, 103));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sisdespesas/img/Plus.png"))); // NOI18N
        jButton2.setText("Cadastrar Usuário");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(49, 43, 103)));
        jButton2.setIconTextGap(8);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtBusca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtBusca.setForeground(new java.awt.Color(49, 43, 103));
        txtBusca.setToolTipText("ToolTipeText");
        txtBusca.setBorder(null);

        jSeparator2.setForeground(new java.awt.Color(49, 43, 103));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(49, 43, 103));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Pesquisar:");
        jLabel4.setToolTipText("");

        btnFiltro.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnFiltro.setForeground(new java.awt.Color(49, 43, 103));
        btnFiltro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sisdespesas/img/loupe.png"))); // NOI18N
        btnFiltro.setToolTipText("Filtrar");
        btnFiltro.setBorder(null);
        btnFiltro.setBorderPainted(false);
        btnFiltro.setContentAreaFilled(false);
        btnFiltro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFiltro.setIconTextGap(8);

        limite.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        limite.setModel(new javax.swing.SpinnerNumberModel(1000, 10, null, 1));
        limite.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(49, 43, 103));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Mostrar:");
        jLabel5.setToolTipText("");

        jSeparator1.setForeground(new java.awt.Color(49, 43, 103));

        btnExportar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnExportar.setForeground(new java.awt.Color(49, 43, 103));
        btnExportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sisdespesas/img/xls.png"))); // NOI18N
        btnExportar.setToolTipText("Exportar como planilha do excel");
        btnExportar.setBorder(null);
        btnExportar.setBorderPainted(false);
        btnExportar.setContentAreaFilled(false);
        btnExportar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExportar.setIconTextGap(8);
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(limite, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2)))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBusca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(limite, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        Exportar.excel(grid, this.getTitle());        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarActionPerformed

    private void gridKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gridKeyReleased
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_INSERT:
                novo();
                break;
            case KeyEvent.VK_DELETE:
                deletar();
                break;
        }
    }//GEN-LAST:event_gridKeyReleased

    private void gridKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gridKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                editar();
                break;
        }
    }//GEN-LAST:event_gridKeyPressed

    private void gridMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridMouseClicked
        if (evt.getClickCount() == 2) {
            editar();
        }
    }//GEN-LAST:event_gridMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        editar();        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        deletar();        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        novo();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnDeletar;
    private javax.swing.JMenuItem btnEditar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnFiltro;
    private javax.swing.JTable grid;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JSpinner limite;
    private javax.swing.JPopupMenu menu;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables

    private void deletar() {
        if (Tabela.is(grid) && Alert.confirm("Você quer apagar este registro?")) {
            if (ControleUsuario.delete(Tabela.get(grid))) {
                btnFiltro.doClick();
                Alert.info("Apaguei o registro para você! =)");
            }
        }
    }

    private void editar() {
        if (Tabela.is(grid)) {
            JDialog modal = new CadastroUsuario(null, true, btnFiltro, Tabela.get(grid));
            modal.setVisible(true);
        }
    }

    private void novo() {
        JDialog modal = new CadastroUsuario(null, true, btnFiltro, null);
        modal.setVisible(true);
    }

}
