/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sisdespesas.view.window;

import br.com.sisdespesas.view.panel.Aplicacao;
import br.com.sisdespesas.view.panel.Login;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author AutoPecasLuz
 */
public class Janela extends javax.swing.JFrame {
private JPanel app; 
    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
        Dimension size = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(size.width, size.height-42);
        setIconImage(new ImageIcon(Janela.class.getResource("/br/com/sisdespesas/img/icone.png")).getImage());
        setLocationRelativeTo(null);
        app = new Login(this);
        this.add(app);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIS DESPESA");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

      

    public void desconectar() {
        Login login = new Login(this);
        this.setTitle("LOGIN");
        login.resetar();
        this.remove(app);
        this.repaint();
        app = login;
        this.add(app);
        login.updateUI();
    }

    public void setHeaderName(String string) {
        this.setTitle(this.getTitle() + " [" + string + "]");
    }

    public void aplicacao(String login) {
        Aplicacao sis = new Aplicacao(this);
        this.setTitle("SIS. DESPESAS");
        this.setHeaderName(login);
        this.remove(app);
        this.repaint();
        app = sis;
        this.add(app);
        sis.updateUI();
    }

}
